image: ubuntu:bionic

stages:
  - tests
  - publish

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  DOCKER_DRIVER: overlay2
  POSTGRES_USER: user
  POSTGRES_DB: db
  POSTGRES_NAME: db
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: corpusops__pgrouting

cache:
  paths:
    - /var/cache/apt/
    - .cache/
    - venv/

before_script: [./install.sh]

tests:
  stage: tests
  tags: [shared-ci-docker]
  services:
    - corpusops/pgrouting:10.1-2.5.4
  script:
    - ./venv/bin/tox -c tox.ini -e coverage
    - ./venv/bin/tox -c tox.ini -e tests
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

linting:
  stage: tests
  tags: [shared-ci-docker]
  script:
     - ./venv/bin/tox -c tox.ini -e linting

publish_pypi:
  image: python:3.6
  stage: publish
  tags: [shared-ci-docker]
  before_script:
    - echo =========== Deploying on pypi ===========
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
  except:
     - branches
  variables:
    TWINE_USERNAME: $PYPI_USER
    TWINE_PASSWORD: $PYPI_PASSWORD
    TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload -r pypi dist/*
