# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.6']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black flake8 isort

    - name: Flake8 check
      run: |
        flake8 terra_bonobo_nodes/ test_terra_bonobo_nodes/

    - name: Black check
      run: |
        black --check terra_bonobo_nodes test_terra_bonobo_nodes

    - name: Isort check
      run: |
        isort -c --profile=black terra_bonobo_nodes/ test_terra_bonobo_nodes/

  build:
    runs-on: ubuntu-18.04
    needs: [lint]
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python-version: ['3.6', '3.8', '3.9']
        django-version: ['2.2.*', '3.2.*']
        experimental: [false]
        include:
          - django-version: '4.0.*'
            python-version: '3.8'
            experimental: true
          - django-version: '4.0.*'
            python-version: '3.9'
            experimental: true
          - django-version: '3.2.*'
            python-version: '3.10'
            experimental: true
          - django-version: '4.0.*'
            python-version: '3.10'
            experimental: true
    services:
      postgres:
        image: postgis/postgis:10-2.5
        env:
          POSTGRES_PASSWORD: db
          POSTGRES_USER: db
          POSTGRES_DB: db
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get -yq install libproj-dev binutils gdal-bin libgdal-dev
        python -m pip install --upgrade pip setuptools wheel
        pip install .[dev] -U
        if [[ ${{ matrix.django-version }} == dev ]]; then
          pip install -e git+https://github.com/django/django@master#egg=django;
        else
          pip install Django==${{ matrix.django-version }} -U;
        fi
    - name: Test with coverage
      run: |
        coverage run ./manage.py test
    - name: Coverage upload
      run: |
        pip install codecov
        codecov
